#!/usr/bin/env python3
"""Generate root-level JupyterLab redirect pages from the student URL workbook."""

from __future__ import annotations

import argparse
import html
import json
import posixpath
import re
import sys
import urllib.parse
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET


NS_MAIN = {"x": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
NS_REL = {"r": "http://schemas.openxmlformats.org/package/2006/relationships"}
OFFICE_REL = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
GENERATED_MARKER = "generated by scripts/generate_student_redirects.py"
SAFE_ENTRY_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


def read_shared_strings(workbook: zipfile.ZipFile) -> list[str]:
    if "xl/sharedStrings.xml" not in workbook.namelist():
        return []

    root = ET.fromstring(workbook.read("xl/sharedStrings.xml"))
    values: list[str] = []
    for item in root.findall("x:si", NS_MAIN):
        text_parts = [
            node.text or ""
            for node in item.iter("{http://schemas.openxmlformats.org/spreadsheetml/2006/main}t")
        ]
        values.append("".join(text_parts))
    return values


def resolve_sheet_path(workbook: zipfile.ZipFile, preferred_sheet: str | None) -> str:
    workbook_root = ET.fromstring(workbook.read("xl/workbook.xml"))
    rels_root = ET.fromstring(workbook.read("xl/_rels/workbook.xml.rels"))
    rels = {rel.attrib["Id"]: rel.attrib["Target"] for rel in rels_root.findall("r:Relationship", NS_REL)}

    selected = None
    for sheet in workbook_root.findall("x:sheets/x:sheet", NS_MAIN):
        if preferred_sheet is None or sheet.attrib.get("name") == preferred_sheet:
            selected = sheet
            break

    if selected is None:
        raise ValueError(f"找不到工作表：{preferred_sheet}")

    rel_id = selected.attrib[f"{{{OFFICE_REL}}}id"]
    target = rels[rel_id]
    if target.startswith("/"):
        return target.lstrip("/")
    return posixpath.normpath(posixpath.join("xl", target))


def cell_column(cell_ref: str) -> str:
    match = re.match(r"([A-Z]+)", cell_ref)
    if not match:
        raise ValueError(f"无法识别单元格位置：{cell_ref}")
    return match.group(1)


def read_cell(cell: ET.Element, shared_strings: list[str]) -> str:
    cell_type = cell.attrib.get("t")
    if cell_type == "inlineStr":
        text_parts = [
            node.text or ""
            for node in cell.iter("{http://schemas.openxmlformats.org/spreadsheetml/2006/main}t")
        ]
        return "".join(text_parts).strip()

    value = cell.find("x:v", NS_MAIN)
    if value is None or value.text is None:
        return ""

    raw = value.text
    if cell_type == "s":
        return shared_strings[int(raw)].strip()
    return raw.strip()


def read_rows(xlsx_path: Path, sheet_name: str | None) -> list[dict[str, str]]:
    with zipfile.ZipFile(xlsx_path) as workbook:
        shared_strings = read_shared_strings(workbook)
        sheet_path = resolve_sheet_path(workbook, sheet_name)
        sheet_root = ET.fromstring(workbook.read(sheet_path))

        rows: list[dict[str, str]] = []
        for row in sheet_root.findall("x:sheetData/x:row", NS_MAIN):
            values: dict[str, str] = {}
            for cell in row.findall("x:c", NS_MAIN):
                values[cell_column(cell.attrib["r"])] = read_cell(cell, shared_strings)
            if values:
                rows.append(values)
        return rows


def parse_students(xlsx_path: Path, sheet_name: str | None) -> list[dict[str, str]]:
    rows = read_rows(xlsx_path, sheet_name)
    if not rows:
        raise ValueError("工作簿为空")

    header_by_name = {value: column for column, value in rows[0].items()}
    required_headers = ["学员", "Linux文件夹", "Jupyter专属链接"]
    missing = [header for header in required_headers if header not in header_by_name]
    if missing:
        raise ValueError(f"缺少必要列：{', '.join(missing)}")

    students: list[dict[str, str]] = []
    for row_number, row in enumerate(rows[1:], start=2):
        student = row.get(header_by_name["学员"], "").strip()
        entry = row.get(header_by_name["Linux文件夹"], "").strip()
        url = row.get(header_by_name["Jupyter专属链接"], "").strip()
        if not any([student, entry, url]):
            continue
        students.append({"row": str(row_number), "student": student, "entry": entry, "url": url})
    return students


def validate_students(students: list[dict[str, str]]) -> None:
    seen_entries: dict[str, str] = {}
    errors: list[str] = []

    for item in students:
        row = item["row"]
        student = item["student"]
        entry = item["entry"]
        url = item["url"]

        if not student or not entry or not url:
            errors.append(f"第 {row} 行存在空值")
            continue

        if not SAFE_ENTRY_RE.fullmatch(entry):
            errors.append(f"第 {row} 行入口不是英文安全格式：{entry}")

        parsed = urllib.parse.urlparse(url)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            errors.append(f"第 {row} 行 Jupyter 专属链接无效：{url}")

        previous = seen_entries.get(entry)
        if previous is not None:
            errors.append(f"入口重复：{entry}，出现在第 {previous} 行和第 {row} 行")
        else:
            seen_entries[entry] = row

    if errors:
        raise ValueError("\n".join(errors))


def redirect_html(target_url: str) -> str:
    escaped_url = html.escape(target_url, quote=True)
    js_url = json.dumps(target_url, ensure_ascii=False)
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex,nofollow,noarchive">
  <meta http-equiv="refresh" content="0; url={escaped_url}">
  <title>正在连接上机服务器</title>
  <!-- {GENERATED_MARKER} -->
  <script>
    window.location.replace({js_url});
  </script>
  <style>
    body {{
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: #222;
      background: #f7f7f5;
    }}
    main {{
      max-width: 36rem;
      padding: 2rem;
      line-height: 1.7;
    }}
    a {{
      color: #0645ad;
    }}
  </style>
</head>
<body>
  <main>
    <h1>正在连接上机服务器</h1>
    <p>如果没有自动跳转，请点击下方链接进入个人上机环境。</p>
    <p><a href="{escaped_url}">进入个人上机环境</a></p>
  </main>
</body>
</html>
"""


def remove_old_redirects(output_dir: Path) -> int:
    removed = 0
    for page in output_dir.glob("*.html"):
        try:
            text = page.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        if GENERATED_MARKER in text:
            page.unlink()
            removed += 1
    return removed


def write_redirects(students: list[dict[str, str]], output_dir: Path) -> int:
    output_dir.mkdir(parents=True, exist_ok=True)
    remove_old_redirects(output_dir)

    for item in students:
        page = output_dir / f"{item['entry']}.html"
        if page.exists():
            raise FileExistsError(f"入口会覆盖已有页面：{page}")
        page.write_text(redirect_html(item["url"]), encoding="utf-8")
    return len(students)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate JupyterLab redirect HTML files.")
    parser.add_argument("--input", default="data/course_students_urls.xlsx", help="student URL workbook")
    parser.add_argument("--output", default="public", help="Hugo output directory")
    parser.add_argument("--sheet", default="course_urls_fixed", help="worksheet name")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_dir = Path(args.output)
    students = parse_students(input_path, args.sheet)
    validate_students(students)
    count = write_redirects(students, output_dir)
    print(f"Generated {count} student redirect pages in {output_dir}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"生成上机入口失败：{exc}", file=sys.stderr)
        raise SystemExit(1)
